@startuml
header Integration - EducaLegal + Docassemble + GED + ESignature
actor User
autonumber

User -> EducaLegal: Clicks Interview
activate EducaLegal

EducaLegal -> Docassemble: Interview Link (url params: tid, ut, intid, doc_uuid)
activate Docassemble

note right
element-tenant-school-interview.yml +
element-tenant-school-interview-error-screens.yml +
module_educalegal_client.py
end note

Docassemble -> EducaLegal: GET tenants_school_names_school_data(tid)
EducaLegal -> Docassemble: school_data_dict{id, name, legal_name, email, school_units, address fields, etc}

Docassemble -> EducaLegal: GET plans_read(plan_id)
EducaLegal -> Docassemble: plan_data{id, name, value, use_ged, plan_type, document_limit, use_esignature, value_currency, use_bulk_interview}

Docassemble -> EducaLegal : GET tenants_read(tid)
EducaLegal -> Docassemble: tenant_data{id, name, auto_enrolled, eua_agreement, etc + esignature_app{name, client_id, provider, private_key, impersonated_user_guid}}

Docassemble -> EducaLegal: GET tenants_ged_read(tid)
EducaLegal -> Docassemble: tenant_ged_data(url, token)
deactivate EducaLegal

Docassemble -> GED: GET document_type_read(interview_document_type)
activate GED

note left
element-tenant-school-interview.yml +
module_mayan_client.py
end note

GED -> Docassemble: document_type_data{id, url, label}
deactivate GED

Docassemble -> EducaLegal: GET interviews_read(intid)
activate EducaLegal


EducaLegal -> Docassemble: interview_data(name, description, version, date, lang, doc type)
deactivate EducaLegal

Docassemble -> User: Shows interview form
deactivate Docassemble

User -> Docassemble: Fills up the interview
activate Docassemble

Docassemble -> EducaLegal: POST elc.patch_document(data, params)
activate EducaLegal

note right
element-educalegal-patch-document.yml +
module_educalegal_client.py
end note

EducaLegal -> Docassemble: returns Educa Legal document data
deactivate Docassemble

EducaLegal -> GED: POST mc.document_create(data, absolute_path)
activate GED

note right
Only if tenant_use_ged == True
mayan_client.py
end note

GED -> EducaLegal: response(many fields, specially document id)
EducaLegal -> GED: GET mc.document_read(created_document_id)
GED -> EducaLegal: created_document_data(status, id, url, uuid)
deactivate GED
EducaLegal -> EducaLegal: atualiza dados do GED no Educa Legal
User -> EducaLegal: Clicks Button to ESignature

EducaLegal -> ESignature: POST send_to_ESignature((recipients, documents, send_immediately, email_subject)
activate ESignature

ESignature -> EducaLegal: envelope_data
EducaLegal -> EducaLegal: atualiza dados do envelope no Educa Legal

ESignature -> Recipients: Send emails
activate Recipients
ESignature -> EducaLegal: POST webhook_listener(statuses changes)
Recipients -> ESignature: Send Signatures
deactivate Recipients

ESignature -> EducaLegal: POST webhook_listener(final status + signed document + certificate)
deactivate ESignature

EducaLegal -> GED: POST mc.document_create(data, absolute_path)
GED -> EducaLegal: dados do documento salvo
deactivate EducaLegal
@enduml