@startuml
header Integration - EducaLegal + Docassemble + Mayan + Docusign
actor User
autonumber
User -> EducaLegal: Clicks Interview
EducaLegal -> Docassemble: Link (tid, ut, intid)
note right
element-tenant-school-interview.yml +
element_educalegal_client.py
end note
activate Docassemble
Docassemble -> EducaLegal: GET tenants_ged_read(tid)
activate EducaLegal
EducaLegal -> Docassemble: tenant_ged_data(url, token)
Docassemble -> EducaLegal: GET tenants_esignature_read(tid)
EducaLegal -> Docassemble: tenant_esignature_data(client_id,impersonated_user_guid,test_mode,private_key)
Docassemble -> EducaLegal: GET tenants_schools_list(tid)*
note over Docassemble
The actual method is 
tenants_school_names_school_data
end note
EducaLegal -> Docassemble: school_data_dict(id, name, legal_name, email, address fields)
Docassemble -> EducaLegal: GET interviews_read(intid)
EducaLegal -> Docassemble: interview_data(name, description, version, date, lang, doc type)
deactivate EducaLegal
Docassemble -> User: Shows interview form
deactivate Docassemble
User -> Docassemble: Fills up the interview
activate Docassemble
note right
element-educalegal-create-document.yml + 
element_educalegal_client.py
end note
Docassemble -> EducaLegal: POST elc.create_document(name, status, description, tenant, school, interview, related_documents, document_data)
activate EducaLegal
EducaLegal -> Docassemble: returns id of document created in Educalegal
deactivate EducaLegal
Docassemble -> Mayan: POST mc.document_create(file, doc_type, file_name, lang, desc)
activate Mayan
note right
Only if tenant_use_ged == True
element-ged.yml + 
element_mayan_client.py +
element_educalegal_client.py
end note
Mayan -> Docassemble: response(many fields, specially document id)
Docassemble -> Mayan: GET mc.document_read(created_document_id)
Mayan -> Docassemble: created_document_data(status, id, url, uuid)
deactivate Mayan
Docassemble -> EducaLegal: PATCH elc.patch_document_with_ged_data(el_document_created_id, cd_ged_id, cd_ged_link, cd_ged_uuid, cd_status)
deactivate Docassemble
User -> Docassemble: Clicks Button to ESignature
activate Docassemble
Docassemble -> Docusign: POST get_signatures
note left
element-esignature.yml
element_docusign.py
end note
activate Docusign
Docusign -> Docassemble: envelope_data
Docassemble -> EducaLegal: PATCH patch_document(ged_id, status, envelope_id, signing_provider)
deactivate Docassemble
activate EducaLegal
Docusign -> Recipients: Send emails
activate Recipients
Recipients -> Docusign: Send Signatures
Docusign -> EducaLegal: POST docusign_webhook_listener(statuses changes)
Recipients -> Docusign: Send Signatures
deactivate Recipients
Docusign -> EducaLegal: POST docusign_webhook_listener(final status + signed document + certificate)
deactivate Docusign
EducaLegal -> Mayan: POST mc.document_create(file, doc_type, file_name, lang, desc)
deactivate EducaLegal
@enduml