version: '3.7'

services:
  nginx:
    container_name: nginx
    build:
      context: dockerfiles/nginx_test
      dockerfile: nginx_test
    ports:
      - "80:80"
      - "443:443"k
    depends_on:
      - api
  educalegal:
    build:
      args:
        BUILD_BACKEND_URL: "https://apitest.educalegal.com.br"
  api:
    command:  gunicorn web.wsgi:application --bind 0.0.0.0:8000 --workers=4 --timeout=300
    environment:
      - DJANGO_SETTINGS_MODULE=web.settings.test
      - EL_ENV=test
    ports:
      - "8000:8000"
  educalegal_celery:
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=web.settings.test
    depends_on:
      - educalegal_rabbitmq