version: '3.7'

services:
  nginx:
    container_name: nginx
    build:
      context: dockerfiles/nginx_test
      dockerfile: nginx_test
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/usr/share/nginx/html
    depends_on:
      - api
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/usr/share/nginx/html
    depends_on:
      - nginx
    command: certonly --webroot --webroot-path=/usr/share/nginx/html --email sistemas@educalegal.com.br --agree-tos --force-renew --non-interactive -d apptest.educalegal.com.br -d apitest.educalegal.com.br
  educalegal:
    build:
      args:
        BUILD_BACKEND_URL: "https://apitest.educalegal.com.br"
  api:
    command:  gunicorn web.wsgi:application --bind 0.0.0.0:8000 --workers=4 --timeout=300
    environment:
      - DJANGO_SETTINGS_MODULE=web.settings.test
      - EL_ENV=test
    ports:
      - "8000:8000"
  apicelery:
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=web.settings.test
    depends_on:
      - apirabbitmq
volumes:
  certbot-etc:
  certbot-var:
  web-root: