# Generated by Django 3.0.4 on 2020-03-06 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interview', '0001_initial'),
        ('tenant', '0001_initial'),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='Nome')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('altered_date', models.DateTimeField(auto_now=True, verbose_name='Alteração')),
                ('signing_provider', models.CharField(max_length=256, verbose_name='Provedor')),
                ('envelope_id', models.CharField(max_length=256, verbose_name='Id do Envelope')),
                ('status', models.CharField(max_length=256, verbose_name='Status')),
                ('ged_id', models.CharField(max_length=128, verbose_name='ID do Documento no GED')),
                ('ged_link', models.CharField(max_length=256, verbose_name='Link')),
                ('ged_uuid', models.CharField(help_text='UUID do documento. UUID = Universally Unique ID.', max_length=256, verbose_name='UUID')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview.Interview', verbose_name='Modelo')),
                ('related_documents', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='document.Document')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.School', verbose_name='Escola')),
                ('tenant', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tenant.Tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentESignatureLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('esignature_log', models.TextField(blank=True, verbose_name='Andamentos da Assinatura Eletrônica')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='document.Document', verbose_name='Documento')),
                ('tenant', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tenant.Tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
