# Generated by Django 3.0.4 on 2020-03-09 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
        ('interview', '0001_initial'),
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='envelope_id',
            field=models.CharField(blank=True, max_length=256, verbose_name='Id do Envelope'),
        ),
        migrations.AlterField(
            model_name='document',
            name='ged_id',
            field=models.CharField(blank=True, max_length=128, verbose_name='ID do Documento no GED'),
        ),
        migrations.AlterField(
            model_name='document',
            name='ged_link',
            field=models.CharField(blank=True, max_length=256, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='document',
            name='interview',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='interview.Interview', verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='document',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.School', verbose_name='Escola'),
        ),
        migrations.AlterField(
            model_name='document',
            name='signing_provider',
            field=models.CharField(blank=True, max_length=256, verbose_name='Provedor'),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(blank=True, max_length=256, verbose_name='Status'),
        ),
    ]
