# Generated by Django 3.0.5 on 2020-04-15 22:14

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_auto_20200309_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True, verbose_name='Dados do Documento'),
        ),
    ]
