# Generated by Django 3.0.5 on 2020-05-01 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_document_document_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='ged_id',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='ID do Documento no GED'),
        ),
        migrations.AlterField(
            model_name='document',
            name='ged_link',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='document',
            name='ged_uuid',
            field=models.CharField(blank=True, help_text='UUID do documento. UUID = Universally Unique ID.', max_length=256, null=True, verbose_name='UUID'),
        ),
    ]
