# Generated by Django 3.0.7 on 2020-06-12 00:08

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


def postgres_migration_prep(apps, schema_editor):
    Document = apps.get_model("document", "Document")
    fields = ("envelope_id", "ged_id", "ged_link", "ged_uuid", "signing_provider", "status")
    for field in fields:
        filter_param = {"{}__isnull".format(field): True}
        update_param = {field: ""}
        Document.objects.filter(**filter_param).update(**update_param)

class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0008_auto_20200514_1100'),
        ('tenant', '0005_auto_20200513_2041'),
        ('document', '0004_auto_20200501_1045'),
    ]

    operations = [
        migrations.RunPython(postgres_migration_prep, migrations.RunPython.noop)

    ]
