# Generated by Django 3.0.7 on 2020-06-12 00:51

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0005_auto_20200611_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='doc_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='UUID'),
        ),
        migrations.AddField(
            model_name='document',
            name='submit_to_esignature',
            field=models.BooleanField(default=False, verbose_name='Enviar para assinatura eletrônica?'),
        ),
        migrations.AddField(
            model_name='document',
            name='task_create_document',
            field=models.CharField(default='', max_length=256, verbose_name='Task de criação de documento'),
        ),
        migrations.AddField(
            model_name='document',
            name='task_submit_to_esignature',
            field=models.CharField(default='', max_length=256, verbose_name='Task de assinatura'),
        ),
        migrations.AlterField(
            model_name='document',
            name='description',
            field=models.TextField(default='', verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='document',
            name='envelope_id',
            field=models.CharField(default='', max_length=256, verbose_name='Id do Envelope'),
        ),
        migrations.AlterField(
            model_name='document',
            name='ged_id',
            field=models.CharField(default='', max_length=128, verbose_name='ID do Documento no GED'),
        ),
        migrations.AlterField(
            model_name='document',
            name='ged_link',
            field=models.CharField(default='', max_length=256, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='document',
            name='ged_uuid',
            field=models.CharField(default='', help_text='UUID do documento. UUID = Universally Unique ID.',
                                   max_length=256, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='document',
            name='signing_provider',
            field=models.CharField(default='', max_length=256, verbose_name='Provedor'),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(default='', max_length=256, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='BulkDocumentGeneration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('field_types_dict',
                 django.contrib.postgres.fields.jsonb.JSONField(default=dict, verbose_name='Campos do Modelo')),
                ('required_fields_dict', django.contrib.postgres.fields.jsonb.JSONField(default=dict,
                                                                                        verbose_name='Obrigatoriedade dos Campos do Modelo')),
                ('parent_fields_dict', django.contrib.postgres.fields.jsonb.JSONField(default=dict,
                                                                                      verbose_name='Objeto que contém o campo')),
                ('school_names_set', django.contrib.postgres.fields.jsonb.JSONField(default=dict,
                                                                                    verbose_name='Conjunto de Nomes de Escola')),
                ('school_units_names_set', django.contrib.postgres.fields.jsonb.JSONField(default=dict,
                                                                                          verbose_name='Conjunto de Nomes de Unidades Escolares')),
                ('mongo_db_collection_name',
                 models.CharField(max_length=1024, verbose_name='Coleção de Documentos no Mongo')),
                ('interview',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='interview.Interview',
                                   verbose_name='Modelo')),
                ('tenant',
                 models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tenant.Tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='document',
            name='bulk_generation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='document.BulkDocumentGeneration', verbose_name='Criação em Lote'),
        ),

    ]
