# Generated by Django 3.0.7 on 2020-06-12 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0006_auto_20200611_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkdocumentgeneration',
            name='status',
            field=models.CharField(default='', max_length=256, verbose_name='Status'),
        ),
    ]
