# Generated by Django 3.0.7 on 2020-06-12 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0007_bulkdocumentgeneration_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='mongo_uuid',
            field=models.CharField(default='', max_length=256, verbose_name='UUID do Mongo'),
        ),
    ]
