# Generated by Django 3.0.7 on 2020-06-14 20:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('document', '0008_document_mongo_uuid'),
    ]

    operations = [
        migrations.RunSQL("""CREATE VIEW document_task AS
                             (SELECT d.id,
                                     d.name,
                                     d.created_date,
                                     d.altered_date,
                                     d.signing_provider,
                                     d.envelope_id,
                                     d.status AS document_status,
                                     d.ged_id,
                                     d.ged_link,
                                     d.ged_uuid,
                                     d.description,
                                     d.interview_id,
                                     d.related_documents_id,
                                     d.school_id,
                                     d.tenant_id,
                                     d.document_data,
                                     d.doc_uuid,
                                     d.submit_to_esignature,
                                     d.task_create_document,
                                     d.task_submit_to_esignature,
                                     d.bulk_generation_id,
                                     d.mongo_uuid,
                                     t.status AS task_status,
                                     t.task_name,
                                     t.date_created as task_created_date,
                                     t.date_done as task_done_date,
                                     t.traceback
                              FROM document_document AS d
                              INNER JOIN django_celery_results_taskresult AS t ON (d.task_create_document = t.task_id
                                                                                   OR d.task_submit_to_esignature = t.task_id))"""
                            )
    ]
