# Generated by Django 3.0.7 on 2020-06-12 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0009_auto_20200614_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvelopeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imported_date', models.DateTimeField(auto_now_add=True, verbose_name='Importação')),
                ('envelope_id', models.CharField(max_length=256, verbose_name='ID')),
                ('status', models.CharField(max_length=256, verbose_name='Status')),
                ('created_date', models.DateTimeField(verbose_name='Criação')),
                ('sent_date', models.DateTimeField(null=True, verbose_name='Envio')),
                ('status_update_date', models.DateTimeField(verbose_name='Alteração do status')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envelops_logs', to='document.Document', verbose_name='Documento')),
            ],
            options={
                'verbose_name': 'Andamento da Assinatura Eletrônica',
                'verbose_name_plural': 'Andamentos da Assinatura Eletrônica',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='SignerLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imported_date', models.DateTimeField(auto_now_add=True, verbose_name='Importação')),
                ('name', models.CharField(max_length=256, verbose_name='Nome')),
                ('email', models.EmailField(max_length=256, verbose_name='E-mail')),
                ('status', models.CharField(max_length=256, verbose_name='Status')),
                ('envelope_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signers_logs', to='document.EnvelopeLog', verbose_name='Andamento da Assinatura Eletrônica')),
            ],
            options={
                'verbose_name': 'Signatário',
                'verbose_name_plural': 'Signatários',
                'ordering': ['-imported_date'],
            },
        ),
        migrations.AddIndex(
            model_name='signerlog',
            index=models.Index(fields=['name'], name='document_si_name_352487_idx'),
        ),
        migrations.AddIndex(
            model_name='signerlog',
            index=models.Index(fields=['email'], name='document_si_email_3579a8_idx'),
        ),
        migrations.AddIndex(
            model_name='signerlog',
            index=models.Index(fields=['status'], name='document_si_status_8af433_idx'),
        ),
        migrations.AddIndex(
            model_name='envelopelog',
            index=models.Index(fields=['envelope_id'], name='document_en_envelop_9aae91_idx'),
        ),
        migrations.AddIndex(
            model_name='envelopelog',
            index=models.Index(fields=['status'], name='document_en_status_396e36_idx'),
        ),
    ]
