# Generated by Django 3.0.7 on 2020-07-01 19:52

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0009_auto_20200614_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTaskView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='Nome')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('altered_date', models.DateTimeField(auto_now=True, verbose_name='Alteração')),
                ('signing_provider', models.CharField(default='', max_length=256, verbose_name='Provedor')),
                ('envelope_id', models.CharField(default='', max_length=256, verbose_name='Id do Envelope')),
                ('document_status', models.CharField(default='', max_length=256, verbose_name='Status do Documento')),
                ('ged_id', models.CharField(default='', max_length=128, verbose_name='ID do Documento no GED')),
                ('ged_link', models.CharField(default='', max_length=256, verbose_name='Link')),
                ('ged_uuid', models.CharField(default='', help_text='UUID do documento. UUID = Universally Unique ID.', max_length=256, verbose_name='UUID')),
                ('description', models.TextField(default='', verbose_name='Descrição')),
                ('document_data', django.contrib.postgres.fields.jsonb.JSONField(null=True, verbose_name='Dados do Documento')),
                ('doc_uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='UUID')),
                ('task_create_document', models.CharField(default='', max_length=256, verbose_name='Task de criação de documento')),
                ('task_submit_to_esignature', models.CharField(default='', max_length=256, verbose_name='Task de assinatura')),
                ('submit_to_esignature', models.BooleanField(default=False, verbose_name='Enviar para assinatura eletrônica?')),
                ('mongo_uuid', models.CharField(default='', max_length=256, verbose_name='UUID do Mongo')),
                ('task_name', models.CharField(max_length=255, null=True, verbose_name='Nome da Task')),
                ('task_status', models.CharField(max_length=50, verbose_name='Status da Task')),
                ('task_created_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criação da Task')),
                ('task_done_date', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Término da Task')),
                ('traceback', models.TextField(blank=True, null=True, verbose_name='Traceback')),
            ],
            options={
                'db_table': 'document_task',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EnvelopeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('altered_date', models.DateTimeField(auto_now=True, verbose_name='Alteração')),
                ('envelope_id', models.CharField(max_length=256, verbose_name='ID')),
                ('status', models.CharField(max_length=256, verbose_name='Status')),
                ('envelope_created_date', models.DateTimeField(verbose_name='Criação do envelope')),
                ('sent_date', models.DateTimeField(null=True, verbose_name='Envio')),
                ('status_update_date', models.DateTimeField(verbose_name='Alteração do status')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envelope_logs', to='document.Document', verbose_name='Documento')),
            ],
            options={
                'verbose_name': 'Andamento da Assinatura Eletrônica',
                'verbose_name_plural': 'Andamentos da Assinatura Eletrônica',
                'ordering': ['-envelope_created_date'],
            },
        ),
        migrations.CreateModel(
            name='SignerLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('name', models.CharField(max_length=256, verbose_name='Nome')),
                ('email', models.EmailField(max_length=256, verbose_name='E-mail')),
                ('type', models.CharField(max_length=256, verbose_name='Tipo')),
                ('status', models.CharField(max_length=256, verbose_name='Status')),
                ('sent_date', models.DateTimeField(blank=True, null=True, verbose_name='Envio')),
                ('pdf_filenames', models.TextField(blank=True, verbose_name='PDFs')),
                ('envelope_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signer_logs', to='document.EnvelopeLog', verbose_name='Andamento da Assinatura Eletrônica')),
            ],
            options={
                'verbose_name': 'Signatário',
                'verbose_name_plural': 'Signatários',
                'ordering': ['-sent_date'],
            },
        ),
        migrations.AddIndex(
            model_name='signerlog',
            index=models.Index(fields=['name'], name='document_si_name_352487_idx'),
        ),
        migrations.AddIndex(
            model_name='signerlog',
            index=models.Index(fields=['email'], name='document_si_email_3579a8_idx'),
        ),
        migrations.AddIndex(
            model_name='signerlog',
            index=models.Index(fields=['status'], name='document_si_status_8af433_idx'),
        ),
        migrations.AddIndex(
            model_name='envelopelog',
            index=models.Index(fields=['envelope_id'], name='document_en_envelop_9aae91_idx'),
        ),
        migrations.AddIndex(
            model_name='envelopelog',
            index=models.Index(fields=['status'], name='document_en_status_396e36_idx'),
        ),
    ]
