# Generated by Django 3.0.7 on 2020-06-27 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0011_auto_20200626_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='task_send_email',
            field=models.CharField(default='', max_length=256, verbose_name='Task de envio de e-mail'),
        ),
    ]
