# Generated by Django 3.0.8 on 2020-07-02 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0013_auto_20200627_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvelopeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('altered_date', models.DateTimeField(auto_now=True, verbose_name='Alteração')),
                ('envelope_id', models.CharField(max_length=256, verbose_name='ID')),
                ('status', models.CharField(max_length=256, verbose_name='Status')),
                ('envelope_created_date', models.DateTimeField(verbose_name='Criação do envelope')),
                ('sent_date', models.DateTimeField(null=True, verbose_name='Envio')),
                ('status_update_date', models.DateTimeField(verbose_name='Alteração do status')),
            ],
            options={
                'verbose_name': 'Andamento da Assinatura Eletrônica',
                'verbose_name_plural': 'Andamentos da Assinatura Eletrônica',
                'ordering': ['-envelope_created_date'],
            },
        ),
        migrations.AlterField(
            model_name='document',
            name='send_email',
            field=models.BooleanField(default=False, verbose_name='E-mail?'),
        ),
        migrations.AlterField(
            model_name='document',
            name='submit_to_esignature',
            field=models.BooleanField(default=False, verbose_name='A Elet'),
        ),
        migrations.CreateModel(
            name='SignerLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('name', models.CharField(max_length=256, verbose_name='Nome')),
                ('email', models.EmailField(max_length=256, verbose_name='E-mail')),
                ('type', models.CharField(max_length=256, verbose_name='Tipo')),
                ('status', models.CharField(max_length=256, verbose_name='Status')),
                ('sent_date', models.DateTimeField(blank=True, null=True, verbose_name='Envio')),
                ('pdf_filenames', models.TextField(blank=True, verbose_name='PDFs')),
                ('envelope_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signer_logs', to='document.EnvelopeLog', verbose_name='Andamento da Assinatura Eletrônica')),
            ],
            options={
                'verbose_name': 'Signatário',
                'verbose_name_plural': 'Signatários',
                'ordering': ['-sent_date'],
            },
        ),
        migrations.AddField(
            model_name='envelopelog',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envelope_logs', to='document.Document', verbose_name='Documento'),
        ),
        migrations.AddIndex(
            model_name='signerlog',
            index=models.Index(fields=['name'], name='document_si_name_352487_idx'),
        ),
        migrations.AddIndex(
            model_name='signerlog',
            index=models.Index(fields=['email'], name='document_si_email_3579a8_idx'),
        ),
        migrations.AddIndex(
            model_name='signerlog',
            index=models.Index(fields=['status'], name='document_si_status_8af433_idx'),
        ),
        migrations.AddIndex(
            model_name='envelopelog',
            index=models.Index(fields=['envelope_id'], name='document_en_envelop_9aae91_idx'),
        ),
        migrations.AddIndex(
            model_name='envelopelog',
            index=models.Index(fields=['status'], name='document_en_status_396e36_idx'),
        ),
    ]
