# Generated by Django 3.0.8 on 2020-07-07 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0006_auto_20200602_1339'),
        ('document', '0014_auto_20200702_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='envelopelog',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tenant.Tenant'),
        ),
        migrations.AddField(
            model_name='signerlog',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tenant.Tenant'),
        ),
        migrations.RunSQL("""update 
  document_envelopelog e  
set 
  tenant_id = d.tenant_id 
from 
  document_document d
where 
  e.document_id = d.id;"""),
        migrations.RunSQL("""update 
  document_signerlog s  
set 
  tenant_id = e.tenant_id 
from 
  document_envelopelog e
where 
  s.envelope_log_id = e.id ;"""),
    ]
