# Generated by Django 3.0.8 on 2020-07-21 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0015_auto_20200707_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='document',
            name='envelope_id',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Id do Envelope'),
        ),
        migrations.AlterField(
            model_name='document',
            name='ged_id',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='ID do Documento no GED'),
        ),
        migrations.AlterField(
            model_name='document',
            name='ged_link',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='document',
            name='ged_uuid',
            field=models.CharField(blank=True, default='', help_text='UUID do documento. UUID = Universally Unique ID.', max_length=256, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='document',
            name='mongo_uuid',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='UUID do Mongo'),
        ),
        migrations.AlterField(
            model_name='document',
            name='signing_provider',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Provedor'),
        ),
        migrations.AlterField(
            model_name='document',
            name='task_create_document',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Task de criação de documento'),
        ),
        migrations.AlterField(
            model_name='document',
            name='task_send_email',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Task de envio de e-mail'),
        ),
        migrations.AlterField(
            model_name='document',
            name='task_submit_to_esignature',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Task de assinatura'),
        ),
    ]
