# Generated by Django 3.0.8 on 2020-07-30 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0006_auto_20200602_1339'),
        ('document', '0016_auto_20200721_0921'),
    ]

    sql_insert_envelopes = """
    INSERT INTO document_envelope 
      (created_date, 
      altered_date, 
      identifier, 
      status, 
      envelope_created_date, 
      sent_date, 
      status_update_date,
      signing_provider, 
      tenant_id,
      envelope_log_id) 
    (SELECT 
      created_date, 
      altered_date, 
      envelope_id, 
      status, 
      envelope_created_date, 
      sent_date, 
      status_update_date, 
      'Docusign',
      tenant_id,
      id
    FROM document_envelopelog el
    order by
      el.id);
        """

    sql_update_documents = """
    update 
      document_document d  
    set 
      envelope_id = e.id 
    from 
      document_envelopelog el inner join
      document_envelope e on
      el.id = e.envelope_log_id 
    where 
      el.document_id = d.id;
        """

    sql_insert_signers = """
    INSERT INTO document_signer 
      (created_date, 
      "name", 
      email, 
      "type", 
      status, 
      sent_date, 
      pdf_filenames, 
      document_id,
      tenant_id, 
      envelope_log_id, 
      signer_log_id) 
    (SELECT 
      sl.created_date, 
      sl."name", 
      sl.email, 
      sl."type", 
      sl.status, 
      sl.sent_date, 
      sl.pdf_filenames, 
      d.id,
      sl.tenant_id, 
      sl.envelope_log_id, 
      sl.id
    FROM document_signerlog sl
    inner join document_envelope e on
      sl.envelope_log_id = e.envelope_log_id 
    inner join document_document d on
      e.id = d.envelope_id 
    order by
      sl.id);
        """

    operations = [
        migrations.CreateModel(
            name='Envelope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('altered_date', models.DateTimeField(auto_now=True, verbose_name='Alteração')),
                ('identifier', models.CharField(max_length=256, verbose_name='ID')),
                ('status', models.CharField(max_length=256, verbose_name='Status')),
                ('envelope_created_date', models.DateTimeField(verbose_name='Criação do envelope')),
                ('sent_date', models.DateTimeField(null=True, verbose_name='Envio')),
                ('status_update_date', models.DateTimeField(null=True, verbose_name='Alteração do status')),
                ('signing_provider', models.CharField(blank=True, default='', max_length=256, verbose_name='Provedor')),
                ('envelope_log_id', models.IntegerField(blank=True, null=True, verbose_name='envelope_log_id')),
            ],
            options={
                'verbose_name': 'Envelope',
                'verbose_name_plural': 'Envelopes',
                'ordering': ['-envelope_created_date'],
            },
        ),
        migrations.CreateModel(
            name='Signer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('name', models.CharField(max_length=256, verbose_name='Nome')),
                ('email', models.EmailField(max_length=256, verbose_name='E-mail')),
                ('type', models.CharField(max_length=256, verbose_name='Tipo')),
                ('status', models.CharField(max_length=256, verbose_name='Status')),
                ('sent_date', models.DateTimeField(blank=True, null=True, verbose_name='Envio')),
                ('pdf_filenames', models.TextField(blank=True, verbose_name='PDFs')),
                ('envelope_log_id', models.IntegerField(blank=True, null=True, verbose_name='envelope_log_id')),
                ('signer_log_id', models.IntegerField(blank=True, null=True, verbose_name='signer_log_id')),
            ],
            options={
                'verbose_name': 'Signatário',
                'verbose_name_plural': 'Signatários',
                'ordering': ['-created_date'],
            },
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-created_date'], 'verbose_name': 'Documento', 'verbose_name_plural': 'Documentos'},
        ),
        migrations.RenameField(
            model_name='document',
            old_name='envelope_id',
            new_name='envelope_number'),
        migrations.RemoveField(
            model_name='document',
            name='signing_provider',
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['envelope_number'], name='document_do_envelop_02edbf_idx'),
        ),
        migrations.AddField(
            model_name='signer',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signers', to='document.Document', verbose_name='Documento'),
        ),
        migrations.AddField(
            model_name='signer',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tenant.Tenant'),
        ),
        migrations.AddField(
            model_name='envelope',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tenant.Tenant'),
        ),
        migrations.AddField(
            model_name='document',
            name='envelope',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='document.Envelope', verbose_name='Envelope'),
        ),
        migrations.AddIndex(
            model_name='signer',
            index=models.Index(fields=['name'], name='document_si_name_dba128_idx'),
        ),
        migrations.AddIndex(
            model_name='signer',
            index=models.Index(fields=['email'], name='document_si_email_ca7735_idx'),
        ),
        migrations.AddIndex(
            model_name='signer',
            index=models.Index(fields=['status'], name='document_si_status_699c46_idx'),
        ),
        migrations.AddIndex(
            model_name='envelope',
            index=models.Index(fields=['identifier'], name='document_en_identif_a4917e_idx'),
        ),
        migrations.AddIndex(
            model_name='envelope',
            index=models.Index(fields=['status'], name='document_en_status_4aad6c_idx'),
        ),
        migrations.RunSQL(sql_insert_envelopes),
        migrations.RunSQL(sql_update_documents),
        migrations.RunSQL(sql_insert_signers),
    ]
