# Generated by Django 3.0.9 on 2020-08-26 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0018_alter_document_task_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='docx_ged_id',
            field=models.CharField(blank=True, max_length=128, verbose_name='ID do Docx do documento no GED'),
        ),
        migrations.AddField(
            model_name='document',
            name='docx_ged_link',
            field=models.CharField(blank=True, max_length=255, verbose_name='Link do Docx'),
        ),
        migrations.AddField(
            model_name='document',
            name='docx_ged_uuid',
            field=models.CharField(blank=True, help_text='UUID do documento em Docx. UUID = Universally Unique ID.', max_length=255, verbose_name='UUID do Docx'),
        ),
        migrations.AlterField(
            model_name='document',
            name='ged_id',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='ID do PDF do documento no GED'),
        ),
        migrations.AlterField(
            model_name='document',
            name='ged_link',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Link do PDF'),
        ),
        migrations.AlterField(
            model_name='document',
            name='ged_uuid',
            field=models.CharField(blank=True, default='', help_text='UUID do documento em PDF. UUID = Universally Unique ID.', max_length=256, verbose_name='UUID do PDF'),
        ),
        migrations.RenameField(
            model_name='document',
            old_name='ged_id',
            new_name='pdf_ged_id'),
        migrations.RenameField(
            model_name='document',
            old_name='ged_link',
            new_name='pdf_ged_link'),
        migrations.RenameField(
            model_name='document',
            old_name='ged_uuid',
            new_name='pdf_ged_uuid'),
    ]
