# Generated by Django 3.1 on 2020-08-18 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0018_alter_document_task_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkdocumentgeneration',
            name='field_types_dict',
            field=models.JSONField(default=dict, verbose_name='Campos do Modelo'),
        ),
        migrations.AlterField(
            model_name='bulkdocumentgeneration',
            name='parent_fields_dict',
            field=models.JSONField(default=dict, verbose_name='Objeto que contém o campo'),
        ),
        migrations.AlterField(
            model_name='bulkdocumentgeneration',
            name='required_fields_dict',
            field=models.JSONField(default=dict, verbose_name='Obrigatoriedade dos Campos do Modelo'),
        ),
        migrations.AlterField(
            model_name='bulkdocumentgeneration',
            name='school_names_set',
            field=models.JSONField(default=dict, verbose_name='Conjunto de Nomes de Escola'),
        ),
        migrations.AlterField(
            model_name='bulkdocumentgeneration',
            name='school_units_names_set',
            field=models.JSONField(default=dict, verbose_name='Conjunto de Nomes de Unidades Escolares'),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_data',
            field=models.JSONField(null=True, verbose_name='Dados do Documento'),
        ),
    ]
