# Generated by Django 3.0.8 on 2020-07-30 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0019_auto_20200826_1603'),
    ]

    operations = [
        migrations.RunSQL("""DROP VIEW IF EXISTS document_task"""),

        migrations.RunSQL("""CREATE VIEW document_task AS
                                 (SELECT d.id,
                                         d.name,
                                         d.created_date,
                                         d.altered_date,
                                         e.signing_provider,
                                         e.identifier AS envelope_id,
                                         d.status AS document_status,
                                         d.ged_id,
                                         d.ged_link,
                                         d.ged_uuid,
                                         d.description,
                                         d.interview_id,
                                         d.parent_id,
                                         d.school_id,
                                         d.tenant_id,
                                         d.document_data,
                                         d.doc_uuid,
                                         d.submit_to_esignature,
                                         d.send_email,
                                         d.task_create_document,
                                         d.task_submit_to_esignature,
                                         d.task_send_email,
                                         d.bulk_generation_id,
                                         d.mongo_uuid,
                                         t.status AS task_status,
                                         t.task_name,
                                         t.date_created as task_created_date,
                                         t.date_done as task_done_date,
                                         t.traceback
                                  FROM document_document AS d
                                  LEFT JOIN document_envelope AS e ON
                                         d.envelope_id = e.id
                                  INNER JOIN django_celery_results_taskresult AS t ON 
                                        (d.task_create_document = t.task_id OR 
                                        d.task_submit_to_esignature = t.task_id OR
                                        d.task_send_email = t.task_id))"""
                          )
    ]
