# Generated by Django 3.1 on 2020-08-20 21:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('document', '0019_auto_20200818_0932'),
    ]

    operations = [
        migrations.RunSQL("""CREATE VIEW document_count AS(
                             SELECT tt.id AS tenant, tt.name AS tenant_name, to_char(dd.created_date, 'mon') as month_name, extract(mon from dd.created_date) as month_number, count(*)
                             FROM document_document AS dd
                                INNER JOIN tenant_tenant AS tt on dd.tenant_id = tt.id
                             GROUP BY tt.id, tt.name, month_name, month_number
                             ORDER BY month_number DESC)"""
                          )
    ]
