# Generated by Django 3.0.9 on 2020-08-26 19:03

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0019_auto_20200818_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='recipients',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, verbose_name='Destinatários do e-mail/assinatura eletrônica'),
        ),
        migrations.RemoveField(
            model_name='document',
            name='related_documents',
        ),
        migrations.AddField(
            model_name='document',
            name='file_kind',
            field=models.CharField(choices=[('PDF', 'pdf'), ('DOCX', 'docx'), ('PDF_SIGNED', 'pdf_signed'),
                                            ('PDF_CERTIFIED', 'pdf_certified')], default='pdf', max_length=255,
                                   verbose_name='Tipo de arquivo'),
        ),
        migrations.AddField(
            model_name='document',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='related_document', to='document.Document'),
        ),
        migrations.AddField(
            model_name='document',
            name='relative_file_path',
            field=models.FileField(blank=True, max_length=255, upload_to='', verbose_name='Caminho relativo do arquivo'),
        ),
    ]
