# Generated by Django 3.0.9 on 2020-09-01 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0020_alter_document_task_view'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='absolute_path',
            new_name='relative_file_path'),
        migrations.AlterField(
            model_name='document',
            name='relative_file_path',
            field=models.FileField(blank=True, max_length=255, upload_to='', verbose_name='Caminho relativo do arquivo'),
        ),
    ]
