# Generated by Django 3.1.1 on 2020-09-15 13:26

from django.db import migrations, models
import web.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0021_alter_document_task_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='cloud_file',
            field=models.FileField(blank=True, max_length=255, storage=web.storage_backends.MediaStorage(), upload_to='', verbose_name='Arquivo na nuvem'),
        ),
        migrations.RemoveField(
            model_name='document',
            name='relative_file_path',
        ),
        migrations.AlterField(
            model_name='document',
            name='recipients',
            field=models.JSONField(blank=True, default=dict, verbose_name='Destinatários do e-mail/assinatura eletrônica'),
        ),
    ]
