# Generated by Django 3.1.1 on 2020-09-17 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0021_alter_document_task_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='recipients',
            field=models.JSONField(blank=True, default=dict, verbose_name='Destinatários do e-mail/assinatura eletrônica'),
        ),
    ]
