pipeline {

   agent any

   stages {
       stage('update_code') {
           steps {
               git (
                   credentialsId: '75810dd9-c7b3-4b29-991d-f8527ddb4f21',
                   url: 'https://github.com/silexsistemas/educalegal.git'
                   )
            }
       }
       stage('update_venv') {
           steps {
               dir('docassemble/docassemble/selenium_tests/'){
                   sh './update_venv.sh'
               }
           }
       }
       stage('test_aditivo-contrato-trabalho-banco-horas') {
           steps {
               catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                    dir('docassemble/docassemble/selenium_tests/'){
                        sh './jenkins_test_aditivo-contrato-trabalho-banco-horas.sh'
                    }
               }
           }
        }
       stage('test_contrato-de-cessao-de-espaco-para-fins-comerciais') {
           steps {
               catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                    dir('docassemble/docassemble/selenium_tests/'){
                        sh './jenkins_test_contrato-de-cessao-de-espaco-para-fins-comerciais.sh'
               }    }
           }
       }
       stage('test_contrato-de-comodato-de-imovel') {
           steps {
               catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                   dir('docassemble/docassemble/selenium_tests/'){
                       sh './jenkins_test_contrato-de-comodato-de-imovel.sh'
                   }
               }
           }
       }
       stage('test_contrato-de-locacao-de-imovel') {
           steps {
               catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                   dir('docassemble/docassemble/selenium_tests/'){
                       sh './jenkins_test_contrato-de-locacao-de-imovel.sh'
                   }
               }
           }
       }
       stage('test_contrato-diretor-estatutario') {
           steps {
               catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                   dir('docassemble/docassemble/selenium_tests/'){
                       sh './jenkins_test_contrato-diretor-estatutario.sh'
                   }
               }
           }
       }
       stage('test_contrato-prestacao-servicos-com-sem-cessao-mao-obra') {
           steps {
               catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                   dir('docassemble/docassemble/selenium_tests/'){
                       sh './jenkins_test_contrato-prestacao-servicos-com-sem-cessao-mao-obra.sh'
                   }
               }
           }
       }
       stage('test_contrato-prestacao-servicos-consultoria') {
           steps {
               catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                   dir('docassemble/docassemble/selenium_tests/'){
                       sh './jenkins_test_contrato-prestacao-servicos-consultoria.sh'
                   }
               }
           }
       }
       stage('test_contrato-prestacao-servicos-educacionais') {
           steps {
               catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                   dir('docassemble/docassemble/selenium_tests/'){
                       sh './jenkins_test_contrato-prestacao-servicos-educacionais.sh'
                   }
               }
           }
       }
       stage('test_notificacao-extrajudicial') {
           steps {
               catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                   dir('docassemble/docassemble/selenium_tests/'){
                       sh './jenkins_test_notificacao-extrajudicial.sh'
                   }
               }
           }
       }
       stage('test_termo-de-autorizacao-do-uso-de-imagem') {
           steps {
               catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                   dir('docassemble/docassemble/selenium_tests/'){
                       sh './jenkins_test_termo-de-autorizacao-do-uso-de-imagem.sh'
                   }
               }
           }
       }
       stage('test_termo-de-confidencialidade-nda') {
           steps {
               catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                   dir('docassemble/docassemble/selenium_tests/'){
                       sh './jenkins_test_termo-de-confidencialidade-nda.sh'
                   }
               }
           }
       }
       stage('test_termo-de-confissao-de-divida') {
           steps {
               catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                   dir('docassemble/docassemble/selenium_tests/'){
                       sh './jenkins_test_termo-de-confissao-de-divida.sh'
                   }
               }

           }
       }
       stage('test_contrato-de-inscricao-em-programa-de-viagem-pedagogica') {
           steps {
               catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                   dir('docassemble/docassemble/selenium_tests/'){
                       sh './jenkins_test_contrato-de-inscricao-em-programa-de-viagem-pedagogica.sh'
                   }
               }
           }
       }
       stage('test_termo-de-uso-e-responsabilidade-iscool-app') {
           steps {
               catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                   dir('docassemble/docassemble/selenium_tests/'){
                       sh './jenkins_test_termo-de-uso-e-responsabilidade-iscool-app.sh'
                   }
               }
           }
       }
       stage('test_acordo-individual-reducao-de-jornada-e-reducao-salarial-mp-936-2020') {
           steps {
               catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                   dir('docassemble/docassemble/selenium_tests/'){
                       sh './jenkins_test_acordo-individual-reducao-de-jornada-e-reducao-salarial-mp-936-2020.sh'
                   }
               }
           }
       }
       stage('test_termo-de-acordo-individual-de-banco-de-horas-mp-927-2020') {
           steps {
               catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                   dir('docassemble/docassemble/selenium_tests/'){
                       sh './jenkins_test_termo-de-acordo-individual-de-banco-de-horas-mp-927-2020.sh'
                   }
               }
           }
       }
       stage('test_termo-home-office-e-direito-autoral') {
           steps {
               catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                   dir('docassemble/docassemble/selenium_tests/'){
                       sh './jenkins_test_termo-home-office-e-direito-autoral.sh'
                   }
               }
           }
       }
       stage('test_acordos-individuais-trabalhistas-coronavirus.py') {
           steps {
               catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                   dir('docassemble/docassemble/selenium_tests/'){
                       sh './jenkins_test_acordos-individuais-trabalhistas-coronavirus.sh'
                   }
               }
           }
       }
       stage('test_proposta-de-renegociacao-contrato-de-locacao.py') {
           steps {
               catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                   dir('docassemble/docassemble/selenium_tests/'){
                       sh './jenkins_test_proposta-de-renegociacao-contrato-de-locacao.sh'
                   }
               }
           }
       }
       stage('test_proposta-de-renegociacao-desconto-no-valor-devido.py') {
           steps {
               catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                   dir('docassemble/docassemble/selenium_tests/'){
                       sh './jenkins_test_proposta-de-renegociacao-desconto-no-valor-devido.sh'
                   }
               }
           }
       }
       stage('test_proposta-de-renegociacao-fluxo-de-pagamento.py') {
           steps {
               catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                   dir('docassemble/docassemble/selenium_tests/'){
                       sh './jenkins_test_proposta-de-renegociacao-fluxo-de-pagamento.sh'
                   }
               }
           }
       }
       stage('test_aditivo-de-reparcelamento-do-contrato-do-aluno.py') {
           steps {
               catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                   dir('docassemble/docassemble/selenium_tests/'){
                       sh './jenkins_test_aditivo-de-reparcelamento-do-contrato-do-aluno.sh'
                   }
               }
           }
       }
       stage('test_termo-de-compromisso-e-rescisao-do-contrato-de-prestacao-de-servicos-educacionais.py') {
           steps {
               catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                   dir('docassemble/docassemble/selenium_tests/'){
                       sh './jenkins_test_termo-de-compromisso-e-rescisao-do-contrato-de-prestacao-de-servicos-educacionais.sh'
                   }
               }
           }
       }
   }
   post {
        always  {
            emailext (
                to: "sistemas@educalegal.com.br",
                subject: "Result: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]'",
                body: """<p>Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]':</p>
                <p>Check console output at &QUOT;<a href='${env.BUILD_URL}'>${env.JOB_NAME} [${env.BUILD_NUMBER}]</a>&QUOT;</p>""",
                attachLog: true
            )
        }
   }
}
