# Generated by Django 3.1 on 2020-09-02 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200818_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='temp_key',
            field=models.CharField(default='', max_length=256, verbose_name='Chave temporária para reset de senha'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='temp_key_created_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Criação da chave temporária'),
        ),
    ]
