# Generated by Django 3.0.6 on 2020-05-14 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interview', '0008_auto_20200514_1100'),
        ('tenant', '0004_auto_20200513_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkGeneration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('source_file', models.FileField(upload_to='')),
                ('interview', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='interview.Interview', verbose_name='Modelo')),
                ('tenant', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tenant.Tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
