# Generated by Django 3.0.6 on 2020-05-20 21:35

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulk_interview', '0002_auto_20200519_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkgeneration',
            name='fields_dict',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}, verbose_name='Campos do Modelo'),
        ),
        migrations.AddField(
            model_name='bulkgeneration',
            name='required_dict',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}, verbose_name='Obrigatoriedade dos Campos do Modelo'),
        ),
    ]
