# Generated by Django 3.0.6 on 2020-05-20 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulk_interview', '0003_auto_20200520_1835'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bulkgeneration',
            old_name='fields_dict',
            new_name='field_types_dict',
        ),
        migrations.RenameField(
            model_name='bulkgeneration',
            old_name='required_dict',
            new_name='required_fields_dict',
        ),
    ]
