# Generated by Django 3.0.6 on 2020-05-28 09:28

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulk_interview', '0004_auto_20200520_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkgeneration',
            name='school_names_set',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, verbose_name='Conjunto de Nomes de Escola'),
        ),
        migrations.AddField(
            model_name='bulkgeneration',
            name='school_units_names_set',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, verbose_name='Conjunto de Nomes de Unidades Escolares'),
        ),
        migrations.AlterField(
            model_name='bulkgeneration',
            name='field_types_dict',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, verbose_name='Campos do Modelo'),
        ),
        migrations.AlterField(
            model_name='bulkgeneration',
            name='required_fields_dict',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, verbose_name='Obrigatoriedade dos Campos do Modelo'),
        ),
    ]
