# Generated by Django 3.0.7 on 2020-06-04 21:35

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulk_interview', '0005_auto_20200528_0628'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkgeneration',
            name='parent_fields_dict',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, verbose_name='Objeto que contém o campo'),
        ),
    ]
