# Generated by Django 3.0.6 on 2020-05-07 21:04

from decimal import Decimal
from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Plano')),
                ('value_currency', djmoney.models.fields.CurrencyField(choices=[('BRL', 'Brazilian Real')], default='BRL', editable=False, max_length=3)),
                ('value', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='BRL', max_digits=14, verbose_name='Valor Mensal')),
                ('document_limit', models.IntegerField(blank=True, null=True, verbose_name='Limite de Documentos')),
            ],
            options={
                'verbose_name': 'Plano',
                'verbose_name_plural': 'Planos',
                'ordering': ['name'],
            },
        ),
    ]
