# Generated by Django 3.0.6 on 2020-05-12 17:28

import billing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='plan_type',
            field=models.CharField(choices=[('ESSENTIAL', 'Essential'), ('STANDARD', 'Standard'), ('PREMIUM', 'Premium'), ('CORPORATE', 'Corporate')], default=billing.models.PlanType['ESSENTIAL'], max_length=30, verbose_name='Tipo de Plano'),
        ),
    ]
