# Generated by Django 3.0.6 on 2020-05-13 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_plan_plan_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='use_bulk_interview',
            field=models.BooleanField(default=False, verbose_name='Usa geração em lote'),
        ),
        migrations.AddField(
            model_name='plan',
            name='use_esignature',
            field=models.BooleanField(default=False, verbose_name='Usa assinatura eletrônica'),
        ),
        migrations.AddField(
            model_name='plan',
            name='use_ged',
            field=models.BooleanField(default=False, verbose_name='Usa gestão eletrônica de documentos'),
        ),
    ]
