# Generated by Django 3.0.6 on 2020-05-21 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_auto_20200513_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='document_limit',
            field=models.IntegerField(blank=True, help_text='Para documentos ilimitados, deixar o campo em branco ou preencher com 0 (zero).', null=True, verbose_name='Limite de Documentos'),
        ),
    ]
