# Generated by Django 3.0.5 on 2020-05-03 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0002_auto_20200421_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='use_bulk_interview',
            field=models.BooleanField(default=False, verbose_name='Usa geração em lote de documentos'),
        ),
    ]
