# Generated by Django 3.0.6 on 2020-05-13 20:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0003_tenant_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='auto_enrolled',
            field=models.BooleanField(default=False, verbose_name='Autoinscrito'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Criação'),
            preserve_default=False,
        ),
    ]
