# Generated by Django 3.0.6 on 2020-05-25 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0005_auto_20200513_2041'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantESignatureApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='Docusign', max_length=255, verbose_name='Fornecedor')),
                ('app_name', models.CharField(default='Educa Legal Development', max_length=255, verbose_name='Nome da Aplicação Cliente')),
                ('private_key', models.TextField(verbose_name='Private Key')),
                ('client_id', models.CharField(help_text='AKA Integration Key', max_length=255, verbose_name='Client ID')),
                ('impersonated_user_guid', models.CharField(blank=True, help_text='AKA API Username', max_length=255, verbose_name='Impersonated User')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('test_mode', models.BooleanField(default=True, verbose_name='Test Mode')),
            ],
        ),
        migrations.AddField(
            model_name='tenant',
            name='esignature_app',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tenant.TenantESignatureApp'),
        ),
    ]
