# Generated by Django 3.0.6 on 2020-06-02 16:39

from django.db import migrations, models
import django.db.models.deletion


def create_demo_e_signature_app(apps, schema_editor):
    # apps.get_model("<nome do app>", "<nome do model>")
    ESignatureApp = apps.get_model("tenant", "ESignatureApp")
    demo_e_signature_app = ESignatureApp(
        private_key="""-----BEGIN RSA PRIVATE KEY-----
MIIEowIBAAKCAQEAg2Vqfmtu8UK389fS7/KmSVpeplTGF1px2JQ+6xjioccZJ77a
ysh80JlL0CQQuXw0ewlQOeVTlKo0g6KZF5cQ/zQqAocqSUJKUmeI1JbtSswv2Nsg
RBOJbzq2dtZweqWWiw8YhhXlAyopJdzJLUMCdeso9VBkUK11W+yFDP+AVNMJEvzI
0rt0Is3jM35+Hr1aTyzk3GtIOE5Lr+ZnIDAW86YTINmNdb7l7MLOwDFsUVa/xOJh
jg+O0QGNuSLBE/AoPsieD7SS40mwjWn7GwmtWBGXf7J1D0Wa3mv0BnnsmXeO1dKN
vQNbqLOD5KlXndyLqzVtO78dmZ+LTUxjsLX6fQIDAQABAoIBAAW0u8EtrS2w9ggS
0Ug2Q15gHEgg2lFdTiBXn7vZ4s2ftcnyEdJIjpMIdTBewJMtf6HwL5m0CcMk+Q7W
WsuZddV/UGu3rvBrforBkEGbJEbhQxqpuWb7ajZ4WEAk49GPq0/yoeAAx2cxx4Or
aNkcVdkFE0xD53dRcQ1C4ixEVDBawcoU+Lxwl+zhmCb9cRhQCdjxn4YgsvDkVoTU
rI+ygjQCexeix4mWlE1+lvKk5oaqWJUJMEvy3Gnw5Df6zV92ExdvMEDCUA6RgcsK
4LZ20rQs7lxYRbATgEnuA4d05VS8H+u4j+ZIKIcrg2J2NI85hOgAjjxilKg+Tyvo
ok4zb0ECgYEAxh2iKtQXSArlJgYiHw7FqFIp2KYGMcHsYkEHqAOH1waMsyxgfUmM
01yBsnB2vuVBbvjsUZ0Cr1+U8i0bKM5bCeCE6PXMrX0gzhQ28J6SUefaP5k4Px9p
deN4KpivZKo8HYABttTsW5dz8LLPkILSd8QZKPaCu5VnNHxYY+xMzYUCgYEAqclj
t/QWYH304RreEqBTnE/QdAnCXE0R6Ju8+s5NxKWd3PnhqQ5SSOMb1MeOrRn4PT44
JW1wJVpHiJQ2m3yAj2P/A1z1ULiYCAYAgrg8PpBzj+oyyWzI3LYF018AQC/dp63s
lBZRwVeWDsoVl9e/xD/ZroH4Gz2zn9YwESSAbpkCgYA78sWafhkZZKqYSezTRw4K
c+pTs1FWhx63UIQ3k/Hr4AB9SyVbZAEoB+r7Csrz0r1tDge8Xm1skdipO3rnayHj
KDwvngk0ShO+KCHDx8fw3t6MthluCFxKHu3Cvfb82AJeztg18dIfmQGtSP5D9UIo
mX8fhRBkIL5dBG9etSc8XQKBgB68bmjmrwZYxvPZQUpt67ToXfwjqCO9b/iD+PoO
TtXChYlzUv6fsRWwx2EFnzaG9QFhOhjMbvjUFw8KhbgwGbXbjFa3hVFPmXYaYA1J
/N32mHT9GKSOJO6PpQ5WrFzyTVYFjkZgo/w0Nt4Gh1ItpHGKfYWx0ZBc4x+UTq9L
xFRBAoGBAI1KXGgAOErBFFGfPVnxxzJ762j8LR7+AmFluWdBvu4gAxu20qsJglFU
+8DeWdg47YIUewjR63VtKLQm7PnkPhjAV3EIsCRGUBxX2FuVJLNm++ohrpih2Kdc
exYcaYWSmH0QjMlnieL/bW8zu+VjwfUOq4JgzwaxvUf31Vk7RmSz
-----END RSA PRIVATE KEY-----""",
        client_id="120eefb3-a639-4ac7-a859-67d997c9222a",
        impersonated_user_guid="916eb776-cab9-48b9-aba9-df63e1d36441",
        notes="Conta de demo: https://account-d.docusign.com/")
    demo_e_signature_app.save()


def create_bahema_e_signature_app(apps, schema_editor):
    # apps.get_model("<nome do app>", "<nome do model>")
    ESignatureApp = apps.get_model("tenant", "ESignatureApp")
    demo_e_signature_app = ESignatureApp(
        name="Bahema",
        private_key="""-----BEGIN RSA PRIVATE KEY-----
MIIEogIBAAKCAQEAhI+rPxItTLdEIxeufYQdlSFLEGI7AbdGmp7L99aafDrSRQ+e
/AUjcqwF+hwOrjHH1qK0T2v07/V6xRLizB0avN/PaUf7Pixv7RcY3/TS90OpK+mx
G/HzLZI3c16DmJmOE9pONvb8jnjtkkKEUqGHA0kGRb7oJm7Ce4Cw5GeXKdcMcWHb
2xAt491gIIlCO4frjQ7KN4yXG41N0Zx5BdI8C2fdaNekyMPe1Wt12WFgl6vJOd2T
ZXy3+uTE6RR7X+e4umb25/+eLVMOqiRrwpJPH9ZZHUUuxsoMVSnh5hvP6bEzQmHe
TEBt/Ikbv7J93T1ONCQ2wj03ntpiZNYQLf667wIDAQABAoIBAB5VU83MZoJCA3z2
O87r7usDoc4fdDopyqWyBaFyQYqA2UHFV896i4h/daSsS+2vZXenZpQv823/Ybb7
4drsJASpQChquMKa34fEu8PvnWDIYksyn/zxigBZD4g+TeWa6aiAUVqBfPxLDq3j
u6y+2oq1aJKII048FRO2uIOjcrM3dapp+KMsnvmQVMJgTtT+kwH76khkvgxcIXEJ
cof2oEm9BbNsH9u3pv2aObm94OXuGk74bkvjX4Drkzec7qKlLPYmo2rW0iBa+CJR
QTrvOBMT7JrmPM+11ySkx6xmQN4sxTok6mZrSqhLg5qrHtlVZJ6G0Cahbd1SKXH0
Gh2CSWECgYEA1Lfi0eAmcquqL+kKsMnIhffxbr8MnQnd0SWu5xKiF+01BFIt4bH3
jGMihW38HNGjq07f94MBzkaae6eiQpXrhmnDrKxg6A8fhkW/4k7x+6iEjnFVOXQH
lYA1uAe6G5wuJ6bnR1v53excSqv8KZM6HsTqkw2s42hkpFmreGtB4qECgYEAn4iL
N8/1dwCG/+3MnJG4+mukkcI15lVrNTGk8R7PNas9VJZLeeAwXp0LD5uvyMY1/6rg
tCmIqBjERUrDotSfliFKa0PV3gSCIoBHjwWh5XmOR0X372rwBzuVdW3I7ztdCgnN
1XifyiuSDlCZcgbnUXmHSERxQH3qzu7cyJtBQ48CgYAl7hwt3FA+xkl0fZOAbpqo
+Ms+OibfobDB6HxFi9cHeS6o9JZl1jwT9mFjdXctFFyg4VGiauPZilFll0ChquXy
c82Gbr5g4sF2Sd2rVvRjMWthkufldMEdcV0i0Y3n+nNocqRu3wGxBsJ2NjCioTQN
5IMHcbrQWf8IJ00iDc4TwQKBgECvb6uAscm/t/1boWQ2nedD8CV9trcfGWonJ/bw
hBoBxctfaVkQcuxaBtscSElDPS/eTGAgmx11dVeXOf3y8oZAF1mo1rW/5DgzBVDT
etJ92BfEIgS8unhkS3SiwB9oVZA1a3VMBJZH1l/hhGY8sFxTx2ug/L6mj6e6KGFa
ujq3AoGASzqMNbXVH1k96HDYbvvEVWoDYDAIsSNHAjfEM8cUF0MrXfKT01f6pDNc
5uUMYZ+eJtgWNbmuFXpqIKXJOhFmoHJ2aerR2yddi3Ynxqml8uzgznYmZ+VpyFyZ
NUib6dhVqcVsbB3DSXX9nqsqjlAlUiKOUF9WedRSTTnuTw+mYyI=
-----END RSA PRIVATE KEY-----""",
        client_id="120eefb3-a639-4ac7-a859-67d997c9222a",
        impersonated_user_guid="02de7724-770a-4a11-8c2c-c6a400d26ae5",
        notes="https://account.docusign.com/",
        test_mode=False)
    demo_e_signature_app.save()


def alter_tenant_bahema(apps, schema_editor):
    # apps.get_model("<nome do app>", "<nome do model>")
    ESignatureApp = apps.get_model("tenant", "ESignatureApp")
    e_signature_bahema_app = ESignatureApp.objects.get(pk=2)

    Tenant = apps.get_model("tenant", "Tenant")
    try:
        tenant_bahema = Tenant.objects.get(name="Bahema")
        tenant_bahema.esignature_app = e_signature_bahema_app
        tenant_bahema.save(update_fields=['esignature_app'])
    except Tenant.DoesNotExist:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0005_auto_20200513_2041'),
    ]

    operations = [
        migrations.CreateModel(
            name='ESignatureApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Educa Legal Development', max_length=255, verbose_name='Nome da Aplicação Cliente')),
                ('provider', models.CharField(default='Docusign', max_length=255, verbose_name='Fornecedor')),
                ('private_key', models.TextField(verbose_name='Private Key')),
                ('client_id', models.CharField(help_text='AKA Integration Key', max_length=255, verbose_name='Client ID')),
                ('impersonated_user_guid', models.CharField(blank=True, help_text='AKA API Username', max_length=255, verbose_name='Impersonated User')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('test_mode', models.BooleanField(default=True, verbose_name='Test Mode')),
            ],
            options={
                'verbose_name': 'Aplicativo de assinatura eletrônica',
                'verbose_name_plural': 'Aplicativos de assinatura eletrônica',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='tenant',
            options={'ordering': ['name'], 'verbose_name': 'Instância', 'verbose_name_plural': 'Instâncias'},
        ),
        migrations.AlterModelOptions(
            name='tenantgeddata',
            options={'ordering': ['tenant'], 'verbose_name': 'Configuração do GED', 'verbose_name_plural': 'Configurações do GED'},
        ),
        migrations.DeleteModel(
            name='TenantESignatureData',
        ),
        migrations.RunPython(create_demo_e_signature_app),
        migrations.AddField(
            model_name='tenant',
            name='esignature_app',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='tenant.ESignatureApp'),
        ),
        migrations.RunPython(create_bahema_e_signature_app),
        migrations.RunPython(alter_tenant_bahema),
    ]
