# Generated by Django 3.0.8 on 2020-07-29 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0006_auto_20200602_1339'),
    ]
    operations = [
        migrations.AddField(
            model_name='tenant',
            name='phone',
            field=models.CharField(max_length=255, blank=True, verbose_name="Telefone"),
        ),
        migrations.RunSQL("""update
  tenant_tenant t
set
  phone = s.phone
from
  school_school s
where
  t.id = s.tenant_id;"""),
        migrations.AlterField(
            model_name='tenant',
            name='phone',
            field=models.CharField(max_length=255, verbose_name="Telefone"),
        ),
    ]