# Generated by Django 3.0.8 on 2020-08-05 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0006_auto_20200602_1339'),
    ]

    sql_update_e_signature_apps = """
    update tenant_esignatureapp 
    set provider = 'DOCUSIGN';"""

    operations = [
        migrations.AlterField(
            model_name='esignatureapp',
            name='provider',
            field=models.CharField(choices=[('CLICKSIGN', 'ClickSign'), ('DOCUSIGN', 'Docusign')], default='ClickSign', max_length=255, verbose_name='Fornecedor'),
        ),
        migrations.RunSQL(sql_update_e_signature_apps),
    ]
