# Generated by Django 3.0.8 on 2020-08-12 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0007_auto_20200805_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='esignature_app',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='tenant.ESignatureApp', verbose_name='App de assinatura eletrônica'),
        ),
        migrations.CreateModel(
            name='ESignatureAppSignerKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='E-mail')),
                ('key', models.CharField(max_length=255, unique=True, verbose_name='Chave')),
                ('tenant', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tenant.Tenant')),
            ],
            options={
                'verbose_name': 'Chave do signatário para assinatura eletrônica',
                'verbose_name_plural': 'Chaves do signatário para assinatura eletrônica',
                'ordering': ['email'],
            },
        ),
        migrations.AddIndex(
            model_name='esignatureappsignerkey',
            index=models.Index(fields=['email'], name='tenant_esig_email_2a7f2f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='esignatureappsignerkey',
            unique_together={('email', 'key')},
        ),
    ]
