# Generated by Django 3.0.9 on 2020-08-18 20:59

from django.db import migrations, models
import django.db.models.deletion

sql_update_e_signature_apps = """
update tenant_esignatureapp 
set provider = 'DOCUSIGN';"""


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0007_tenant_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esignatureapp',
            name='provider',
            field=models.CharField(choices=[('CLICKSIGN', 'ClickSign'), ('DOCUSIGN', 'Docusign')], default='ClickSign', max_length=255, verbose_name='Fornecedor'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='esignature_app',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='tenant.ESignatureApp', verbose_name='App de assinatura eletrônica'),
        ),
        migrations.CreateModel(
            name='ESignatureAppSignerKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, verbose_name='E-mail')),
                ('key', models.CharField(max_length=255, verbose_name='Chave')),
                ('tenant', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tenant.Tenant')),
            ],
            options={
                'verbose_name': 'Chave do signatário para assinatura eletrônica',
                'verbose_name_plural': 'Chaves do signatário para assinatura eletrônica',
                'ordering': ['email'],
                'unique_together': {('email', 'tenant')},
            },
        ),
        migrations.RunSQL(sql_update_e_signature_apps),
    ]
