# Generated by Django 3.0.9 on 2020-08-21 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0008_auto_20200818_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='esignatureappsignerkey',
            name='esignature_app',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, to='tenant.ESignatureApp', verbose_name='App de assinatura eletrônica'),
        ),
        migrations.AlterUniqueTogether(
            name='esignatureappsignerkey',
            unique_together={('email', 'tenant', 'esignature_app')},
        ),
    ]
