# Generated by Django 3.0.9 on 2020-09-01 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0009_auto_20200821_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='esignature_folder',
            field=models.CharField(blank=True, max_length=255, verbose_name='Pasta para upload dos documentos'),
        ),
    ]
