# Generated by Django 3.0.4 on 2020-03-09 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='letterhead',
            field=models.CharField(default='timbrado.docx', max_length=255, verbose_name='Timbrado'),
            preserve_default=False,
        ),
    ]
