# Generated by Django 3.0.4 on 2020-03-22 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tenant", "0001_initial"),
        ("school", "0004_auto_20200316_1033"),
    ]

    operations = [
        migrations.AlterField(
            model_name="school",
            name="cnpj",
            field=models.CharField(max_length=255, verbose_name="CNPJ"),
        ),
        migrations.CreateModel(
            name="SchoolUnit",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=255, verbose_name="Nome"),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="school_units",
                        to="school.School",
                        verbose_name="Unidade Escolar",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenant.Tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Unidade Escolar",
                "verbose_name_plural": "Unidades Escolares",
                "ordering": ["name"],
            },
        ),
    ]
