# Generated by Django 3.0.5 on 2020-05-04 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('school', '0006_auto_20200503_2024'), ('school', '0007_auto_20200503_2132')]

    dependencies = [
        ('school', '0005_auto_20200322_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='country',
        ),
        migrations.AlterField(
            model_name='school',
            name='city',
            field=models.CharField(max_length=255, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='school',
            name='country',
            field=models.CharField(default='Brasil', max_length=255, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='school',
            name='letterhead',
            field=models.CharField(default='timbrado-pradrao.docx', max_length=255, verbose_name='Timbrado'),
        ),
        migrations.AlterField(
            model_name='school',
            name='state',
            field=models.CharField(max_length=255, verbose_name='Estado'),
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='State',
        ),
        migrations.AlterField(
            model_name='school',
            name='cnpj',
            field=models.CharField(max_length=255, verbose_name='CNPJ/CPF'),
        ),
    ]
