# Generated by Django 3.0.5 on 2020-05-04 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_auto_20200503_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='letterhead',
            field=models.CharField(default='timbrado-padrao.docx', max_length=255, verbose_name='Timbrado'),
        ),
    ]
