# Generated by Django 3.0.8 on 2020-08-11 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_school_created_date'),
        ('school', '0010_auto_20200810_1644'),
    ]

    operations = [
    ]
