# Generated by Django 3.0.8 on 2020-08-10 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_school_esignature_folder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='legal_type',
            new_name='legal_nature',
        ),
    ]
