# Generated by Django 3.1.1 on 2020-09-18 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0012_auto_20200824_1402'),
        ('school', '0013_auto_20200917_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolunit',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='schoolunit',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_units', to='school.school', verbose_name='Escola'),
        ),
        migrations.CreateModel(
            name='Witness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('cpf', models.CharField(blank=True, max_length=255, verbose_name='CPF')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='witnesses', to='school.school', verbose_name='Escola')),
                ('tenant', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Testemunha',
                'verbose_name_plural': 'Testemunhas',
                'ordering': ['name'],
            },
        ),
    ]
