# Generated by Django 3.1.3 on 2020-11-13 17:00

from django.db import migrations, models
import django.db.models.deletion
import school.models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0012_auto_20200824_1402'),
        ('school', '0015_auto_20201028_1405'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Witness',
            new_name='SigningPerson',
        ),
        migrations.AddField(
            model_name='signingperson',
            name='signing_person_kind',
            field=models.CharField(choices=[('WITNESS', 'Testemunha'), ('REPRESENTATIVE', 'Representante')],
                                   default=school.models.SigningPersonKind['WITNESS'],
                                   max_length=255,
                                   verbose_name='Tipo de Signatário da Escola')
        ),
        migrations.AlterModelOptions(
            name='signingperson',
            options={'ordering': ['name'], 'verbose_name': 'Signatário da Escola',
                     'verbose_name_plural': 'Signatários da Escola'},
        ),
        migrations.AlterField(
            model_name='signingperson',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signing_people',
                                    to='school.school', verbose_name='Escola'),
        ),
    ]