# Generated by Django 3.0.5 on 2020-04-20 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0002_tenant_eua_agreement'),
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='tenants',
            field=models.ManyToManyField(to='tenant.Tenant'),
        ),
    ]
