# Generated by Django 3.0.6 on 2020-05-21 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0002_auto_20200421_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='custom_file_name',
            field=models.CharField(max_length=255, verbose_name='Nome do arquivo a ser gerado'),
        ),
    ]
