# Generated by Django 3.0.6 on 2020-05-08 21:48

from django.db import migrations, models
import django.db.models.deletion


def create_default_server_config(apps, schema_editor):
    # apps.get_model("<nome do app>", "<nome do model>")
    ServerConfig = apps.get_model("interview", "ServerConfig")
    default_server_config = ServerConfig(
        name="Produção",
        base_url="https://docs.educalegal.com.br",
        user_id="1",
        username="admin@admin.com",
        user_key="C3vAIRNnr3BnJpKCdqlsXSV2fLWPKI0K",
        user_password="Silex2109",
        project_name="Production")
    default_server_config.save()


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0002_auto_20200421_2002'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nome')),
                ('base_url', models.CharField(max_length=255, verbose_name='URL Base')),
                ('user_id', models.IntegerField()),
                ('username', models.CharField(max_length=255)),
                ('user_key', models.CharField(max_length=255)),
                ('user_password', models.CharField(max_length=255)),
                ('project_name', models.CharField(default='Default', max_length=255, verbose_name='Nome do projeto')),
            ],
            options={
                'verbose_name': 'Configuração do Servidor',
                'verbose_name_plural': 'Configurações do servidor',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='interview',
            name='use_bulk_interview',
            field=models.BooleanField(default=False, verbose_name='Usa geração em lote?'),
        ),
        migrations.AddField(
            model_name='interview',
            name='yaml_name',
            field=models.CharField(default='yml', max_length=255, verbose_name='Nome do YAML'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='base_url',
            field=models.CharField(max_length=512, verbose_name='URL Base'),
        ),
        migrations.RunPython(create_default_server_config),
        migrations.AddField(
            model_name='interview',
            name='server_config',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='interviews', to='interview.ServerConfig'),
        ),
    ]
