# Generated by Django 3.0.5 on 2020-05-13 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0003_auto_20200508_1848'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServerConfig',
            new_name='InterviewServerConfig',
        ),
        migrations.AlterModelOptions(
            name='interviewserverconfig',
            options={'ordering': ['name'], 'verbose_name': 'Configuração do Servidor de Entrevistas', 'verbose_name_plural': 'Configurações do Servidor de Entrevistas'},
        ),
        migrations.RemoveField(
            model_name='interview',
            name='server_config',
        ),
        migrations.AddField(
            model_name='interview',
            name='interview_server_config',
            field=models.ForeignKey(default=1, help_text='Configuração do Servidor de Entrevistas usado para montar a URL da entrevista. Esse valor é sobrescrito se o valor URL customizada for preenchido.', on_delete=django.db.models.deletion.PROTECT, related_name='interviews', to='interview.InterviewServerConfig', verbose_name='Servidor de Entrevistas'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='base_url',
            field=models.URLField(default='', help_text='O valor desse campo sobrescreve qualquer valor de configuração de Servidor de Entrevistas. Deve ser usado para inserir URLs arbitrárias de entrevistas.', verbose_name='URL Customizada'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='is_freemium',
            field=models.BooleanField(default=False, help_text='Se marcado, a entrevista é disponibilizada para os tenants que se auto inscreve no site', verbose_name='É Freemium?'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='is_generic',
            field=models.BooleanField(default=True, help_text='Se marcado, insere na URL da entrevista os parâmetros de acesso (tenand id, user token, e interview id)', verbose_name='Inserir dados de acesso?'),
        ),
    ]
