# Generated by Django 3.0.5 on 2020-05-13 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0004_auto_20200513_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='base_url',
            field=models.URLField(default='', help_text='O valor desse campo sobrescreve qualquer valor de configuração de Servidor de Entrevistas. Deve ser usado para inserir URLs arbitrárias de entrevistas.', null=True, verbose_name='URL Customizada'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='is_freemium',
            field=models.BooleanField(default=False, help_text='Se marcado, a entrevista é disponibilizada para o cliente (tenant) que se auto inscreve no site.', verbose_name='É Freemium?'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='is_generic',
            field=models.BooleanField(default=True, help_text='Se marcado, insere na URL da entrevista os parâmetros de acesso (tenand id, user token, e interview id).', verbose_name='Inserir dados de acesso?'),
        ),
    ]
