# Generated by Django 3.0.5 on 2020-05-13 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0005_auto_20200513_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='base_url',
            field=models.URLField(blank=True, default='', help_text='O valor desse campo sobrescreve qualquer valor de configuração de Servidor de Entrevistas. Deve ser usado para inserir URLs arbitrárias de entrevistas.', null=True, verbose_name='URL Customizada'),
        ),
    ]
