# Generated by Django 3.0.6 on 2020-05-14 14:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0007_auto_20200513_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='date_available',
            field=models.DateField(default=datetime.date.today, verbose_name='Disponibilização'),
        ),
    ]
