version: '3'

services:
  web:
    environment:
      - DATABASE_NAME=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
    ports:
      - "8000:8000"
    depends_on:
      - db
      - docassemble
  db:
    container_name: db
    image: postgres:11-alpine
  docassemble:
    container_name: docassemble
    image: jhpyle/docassemble:latest
    environment:
      - DAPYTHONVERSION=3
    ports:
      - "80:80"