version: '3.7'

services:
  educalegal_front:
    image: rvnovaes/educalegal-front:0.3
    container_name: educalegal_front
    restart: unless-stopped
    build:
      context: ../front
#      args:
#        BACKEND_URL: "http://educalegal:8008"
    depends_on:
      - educalegal
    ports:
      - "3000:3000"
  educalegal:
    image: rvnovaes/educalegal:2.0
    container_name: educalegal
    restart: unless-stopped
    build: .
    command: ["./wait-for-postgres.sh", "python", "./manage.py", "runserver 0.0.0.0:8008"]
    volumes:
      - type: bind
        source: .
        target: /code
      - type: bind
        source: ./media
        target: /code/media
    environment:
      - DJANGO_SETTINGS_MODULE=web.settings.development_docker
      - EL_ENV=development
      - SENDGRID_API_KEY=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
    depends_on:
      - educalegal_rabbitmq
      - mongo
  educalegal_celery:
    image: rvnovaes/educalegal:2.0
    container_name: educalegal_celery
    build: .
    command: celery -A web worker -l info -c 1 -n educalegalworker1@%h
    volumes:
      - type: bind
        source: .
        target: /code
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=web.settings.development_docker
    depends_on:
      - educalegal_rabbitmq
  educalegal_flower:
    container_name: educalegal_flower
    image: mher/flower
    environment:
      - CELERY_BROKER_URL=amqp://educalegal:educalegal@educalegal_rabbitmq/educalegal
      - FLOWER_BASIC_AUTH=educalegal:cavaloverdegrande
      - FLOWER_PORT=8888
    depends_on:
      - educalegal_rabbitmq
    ports:
      - "8888:8888"
  educalegal_rabbitmq:
    container_name: educalegal_rabbitmq
    image: rabbitmq:3.8.4-management
    environment:
      RABBITMQ_DEFAULT_USER: educalegal
      RABBITMQ_DEFAULT_PASS: educalegal
      RABBITMQ_DEFAULT_VHOST: educalegal
    ports:
      - "5672:5672"
      - "9999:15672"
    volumes:
      - /opt/educalegal/docker_volumes/rabbitmq_app:/var/lib/rabbitmq
  mongo:
    image: mongo:4.2.6
    container_name: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: educalegal
      MONGO_INITDB_ROOT_PASSWORD: educalegal
      MONGO_INITDB_DATABASE: educalegal
      MONGO_INITDB_USERNAME: educalegal
      MONGO_INITDB_PASSWORD: educalegal
    volumes:
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
      - /opt/educalegal/docker_volumes/mongo_db:/data/db
    ports:
      - "27017:27017"
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: educalegal
      ME_CONFIG_BASICAUTH_PASSWORD: cavaloverdegrande
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: educalegal
      ME_CONFIG_MONGODB_ADMINPASSWORD: educalegal
    depends_on:
      - mongo
    ports:
      - "8081:8081"