version: '3.7'

services:
#  web_server:
#    container_name: web_server
#    build:
#      context: nginx_dockerfile_prod
#      dockerfile: Dockerfile
#    restart: unless-stopped
#    ports:
#      - "80:80"
#      - "443:443"
#    depends_on:
#      - educalegal
#      - educalegal_front
  educalegal:
    build:
      args:
        BUILD_BACKEND_URL: "https://api.educalegal.com.br"
  api:
    command:  gunicorn web.wsgi:application --bind 0.0.0.0:8000 --workers=4 --timeout=300
    environment:
      - DJANGO_SETTINGS_MODULE=web.settings.production
      - EL_ENV=production
    ports:
      - "8000:8000"
  educalegal_celery:
    environment:
      - DEBUG=0
      - DJANGO_SETTINGS_MODULE=web.settings.production
    depends_on:
      - educalegal_rabbitmq