version: '3.7'

services:
  educalegal:
    # Os settings do banco devem ficar aqui tambem para permitir que o script wait for postgres funcione
    environment:
      DATABASE_NAME: educalegal
      DATABASE_USER: educalegal
      DATABASE_PASSWORD: educalegal
      DATABASE_HOST: db
      DATABASE_PORT: 5432
    ports:
      - "8008:8008"
    depends_on:
      - db
      - docassemble
      - ged
  docassemble:
    container_name: docassemble
    image: jhpyle/docassemble:latest
    environment:
      - DAPYTHONVERSION=3
      - TIMEZONE=America/Sao_Paulo
      - LANGUAGE=pt
      - LOCALE=pt_BR.utf8
      - DAWEBSERVER=nginx
      - SERVERADMIN=sistemas@educalegal.com.br
      - PYTHONPACKAGES=docassemble-wrappers,num2words,validator-collection-br,retry-requests,sendgrid
    ports:
      - "80:80"
    volumes:
      - ./fonts/calibri:/usr/share/fonts/calibri
  ged:
    container_name: ged
    image: mayanedms/mayanedms:3.4.13
    environment: &mayan_env
      MAYAN_CELERY_BROKER_URL: amqp://mayan:mayanrabbitpass@rabbitmq_ged:5672/mayan
      MAYAN_CELERY_RESULT_BACKEND: "redis://:mayanredispassword@redis:6379/0"
      MAYAN_DATABASES: "{'default':{'ENGINE':'django.db.backends.postgresql','NAME':'mayan','PASSWORD':'mayandbpass','USER':'mayan','HOST':'db_ged'}}"
      MAYAN_APT_INSTALLS: "tesseract-ocr-deu tesseract-ocr-spa tesseract-ocr-por tesseract-ocr-fra"
    volumes:
      - /opt/educalegal/docker_volumes/mayan:/var/lib/mayan
    ports:
      - "8000:8000"
    depends_on:
      - db_ged
      - redis
  redis:
    container_name: redis
    image: redis:5.0-alpine
    command:
      - redis-server
      - --databases
      - "2"
      - --maxmemory-policy
      - allkeys-lru
      - --save
      - ""
      - --requirepass mayanredispassword
    volumes:
      - /opt/educalegal/docker_volumes/redis:/data
  rabbitmq_ged:
    container_name: rabbitmq_ged
    image: healthcheck/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: mayan
      RABBITMQ_DEFAULT_PASS: mayanrabbitpass
      RABBITMQ_DEFAULT_VHOST: mayan
    volumes:
      - /opt/educalegal/docker_volumes/rabbitmq_ged:/var/lib/rabbitmq
  celery_flower_ged:
    container_name: celery_flower_ged
    command:
      - run_celery
      - flower
    depends_on:
      - db_ged
      - redis
      - rabbitmq_ged
    environment:
      <<: *mayan_env
    image: mayanedms/mayanedms:3
    ports:
      - "5555:5555"
  db:
    container_name: db
    image: postgres:11-alpine
    volumes:
    - /opt/educalegal/docker_volumes/postgres_db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: educalegal
      POSTGRES_USER: educalegal
      POSTGRES_PASSWORD: educalegal
    ports:
      - "7654:5432"
  db_ged:
    container_name: db_ged
    image: postgres:11-alpine
    environment:
      POSTGRES_DB: mayan
      POSTGRES_USER: mayan
      POSTGRES_PASSWORD: mayandbpass
    ports:
      - "6543:5432"
    volumes:
      - /opt/educalegal/docker_volumes/postgres_db_ged:/var/lib/postgresql/data