version: '3'

services:
  db:
    image: postgres:11
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - docassemble
  docassemble:
    image: jhpyle/docassemble
    environment:
      - DAPYTHONVERSION=3
    ports:
      - "80:80"